spring:
  application:
    name: gluns-spring
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:mysql://gluns-spring-mysql:3306/db_gluns-spring-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # create | update | validate | none | create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8083
  
# -------------- External Services Configuration --------------
gluns:
  python:
    url: http://python-back:8000 # http://localhost:8000 | http://gluns-python:8000

# -------------- OpenAPI --------------
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    syntax-highlight:
      theme: agate
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

# ------------------------ Logging ------------------------
logging:
  level:
    org.springframework.security: info # trace | debug | info | warn | error | fatal | off
    org.springframework.cloud.gateway: info
    org.springframework.boot: info
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    org.gluns.glunsspring.infrastructure.adapters.out.keycloak: debug

# ------------------------ keycloak ------------------------
keycloak:
  realm: realm-test
  base-uri: ${KEYCLOAK_SERVER:http://localhost}:8080/realms/${keycloak.realm}
  jwk-set-uri: ${keycloak.base-uri}/protocol/openid-connect/certs
  certs-id: ${KEYCLOACK_REAL_ID:5pzY9Px9dJFUtHDTQHLKrggQidd4p1IbEfSM6e8aZwY}
  token-uri: ${keycloak.base-uri}/protocol/openid-connect/token
  user-info-uri: ${keycloak.base-uri}/protocol/openid-connect/userinfo
  logout: ${keycloak.base-uri}/protocol/openid-connect/logout
  client-id: front-gluns-app
  authorization-grant-type: password
  authorization-grant-type-refresh: refresh_token
