spring:
  application:
    name: gluns-spring
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:mysql://localhost:3306/db_gluns-spring-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        
server:
  port: 8083

# -------------- OpenAPI --------------
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    syntax-highlight:
      theme: agate
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
    
# ------------------------ Logging ------------------------
logging:
  level:
    org.springframework.security: info # trace | debug | info | warn | error | fatal | off
    org.springframework.cloud.gateway: info
    org.springframework.boot: info
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF