spring:
  application:
    name: gluns-spring
  main:
    web-application-type: reactive
    
# -------------- OpenAPI --------------
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
# ------------------------ Logging ------------------------
logging:
  level:
    org.springframework.security: info # trace | debug | info | warn | error | fatal | off
    org.springframework.cloud.gateway: info
    org.springframework.boot: info
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF